customLines: 6
randomLines: 4

full:
    - Wow
    - Pls play

prefix:
    - Such
    - Much
    - So
    - Very
    - Many

suffix:
    - Minceraft
    - dig
    - blocks
    - pixels
    - amuse
    - fun
    - game
    - diamonds

colors: [6,9,a,b,c,d,e,f]

broadcastSender: true
broadcastMessage: '%6%%player% summoned Doge using /wow !'

debug: false